services:
  auth_service:
    build: ./auth_services
    ports:
      - "5001:5000"  # external:internal
    env_file:
      - ./auth_services/.env

  task_service:
    build: ./task_service
    ports:
      - "5002:5002"
    env_file:
      - ./task_service/.env
    depends_on:
      - auth_service

  api_gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    env_file:
      - ./gateway/.env
    depends_on:
      - auth_service
      - task_service

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api_gateway
networks:
  micro_net:
    driver: bridge
